// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRZV54C7AvCcFjqJ6LSWQWz4rVnClqfB0',
    appId: '1:1006448945386:web:5347692439d5e90f484f93',
    messagingSenderId: '1006448945386',
    projectId: 'flutter-firebase-codex',
    authDomain: 'flutter-firebase-codex.firebaseapp.com',
    storageBucket: 'flutter-firebase-codex.appspot.com',
    measurementId: 'G-71TTW0Z77V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMVDefrTV87IWCZwjNhHhcMvqPrB48S0',
    appId: '1:1006448945386:android:69f98bfa4aefaa8e484f93',
    messagingSenderId: '1006448945386',
    projectId: 'flutter-firebase-codex',
    storageBucket: 'flutter-firebase-codex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAfm3tvcp7pS8BzR86PHWNJitCOiVl1Y0',
    appId: '1:1006448945386:ios:97b93e7982bc80ee484f93',
    messagingSenderId: '1006448945386',
    projectId: 'flutter-firebase-codex',
    storageBucket: 'flutter-firebase-codex.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAfm3tvcp7pS8BzR86PHWNJitCOiVl1Y0',
    appId: '1:1006448945386:ios:90f027370b36ea8c484f93',
    messagingSenderId: '1006448945386',
    projectId: 'flutter-firebase-codex',
    storageBucket: 'flutter-firebase-codex.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
